utils::globalVariables(c(
  "doi", "name", "type", "language", "method.x", "method.y", "is_oa", "oa_status",
  "decision", "status", "article", "moduleServer", "NS", "reactive", "observe",
  "updatePickerInput", "pickerInput", "tagList", "renderPlotly", "setNames",
  "plot_ly", "layout", "updateSelectizeInput", "observeEvent", "updateSliderInput",
  "withSpinner", "fluidRow", "sliderInput", "uid", "title", "abstract", "keywords",
  "strings", "Status", "frequency", "unknown", "pathStatus", "box", "plotlyOutput",
  "head", "write.csv", "use_virtualenv", "py_config", "txt_path", "blind", "random",
  "welfare", "interest", "is_blind", "is_random", "is_exclusion", "is_welfare",
  "is_interest", "exclusion", "fold", "threshold", "correction_needed", "item_id",
  "score", "label", "new_total_to_re_screen", "LABEL", "data", "CreateMLFilenames",
  "WriteFilesForIOE", "CreateFileNamesForIOEAPI", "TrainCollection", "FindBestPerformance",
  "read_csv", "ITEM_ID", "Chosen", "cid", "decision", "Balanced.Accuracy", "booktitle",
  "pages", "start_page", "end_page", "article_id", "AN", "runif", "pubmed_id",
  "setNames", "record_id", "article_ids", "JS", "HTML", "pickerOptions", "selectizeInput",
  "downloadHandler", "renderUI", "reactiveValues", "str_trim", "str_replace_all",
  "str_split", "withProgress", "incProgress", "isolate", "shinyalert", "renderText",
  "toTitleCase", "downloadBttn", "animateOptions", "tooltipOptions", "prettySwitch",
  "br", "p", "icon", "div", "dropdown", "uiOutput", "tagList", "radioGroupButtons",
  "actionBttn", "animations", "tail", "field_specific_repo", "accession_nr", "available", "not_available",
  "was_available", "repositories", "github", "source_code", "upon_request",
  "supplement", "publ_sentences", "com_specific_repo", "com_general_repo",
  "com_github_data", "dataset", "com_code", "com_suppl_code", "str_remove_all",
  "str_to_title", "AB", "ABSTRACT", "AU", "Abstract", "Alternate Name",
  "AlternateName", "Author Address", "AuthorAddress", "Authors", "Cat",
  "CustomId", "DOI", "Doi", "KEYWORDS", "Keywords", "PA", "PDF Relative Path",
  "PY", "PdfRelativePath", "Publication Name", "PublicationName", "REVIEW_ID",
  "Reference Type", "ReferenceType", "T2", "TI", "TITLE", "Title", "Url", "Year",
  "accession", "alternate_names", "area", "au_display_name", "auth_match",
  "author", "author.x", "author.y", "author_affiliation", "author_country",
  "author_orig", "author_position", "best_oa_location", "chosen", "column",
  "com_data_availibility", "com_file_formats", "com_supplemental_data",
  "con", "content.type", "custom_id", "date_filename", "date_time_of_screening",
  "doi.y", "doi_fixed", "domain", "download.file", "error_corrected",
  "eventReactive", "final_match", "first_page", "format_as_sunburst", "ft_path",
  "is_data_journal", "is_general_purpose", "is_new", "is_open_code", "is_open_data",
  "is_supplement", "is_valid", "isbn", "issn", "issue", "jour_match", "journal",
  "keywords_id", "last_page", "link", "main_category", "match_type", "materialSwitch",
  "method", "name_detected", "new_decision", "new_decision_date", "new_doi",
  "not_available", "number", "open_code_statements", "open_data_category",
  "open_data_statements", "page_match", "pages_new", "path", "pdf", "pmid",
  "ptype", "publ_sentences", "published_year", "read.xlsx", "record_ids", "regex",
  "regex_id", "regex_ont", "repositories", "scopus_accession", "screening_status",
  "secondarytitle", "so", "source_code", "source_type", "status.x", "sub_category1",
  "sub_category2", "supplement", "systematic_search_name", "tabBox", "tabPanel",
  "tags", "tail", "textAreaInput", "textOutput", "timestamp", "total_new_rob_tag",
  "type_new", "updateTextAreaInput", "upon_request", "user", "ut", "volume",
  "was_available", "wos_accession", "write.table", ".", "file_size", "filename",
  "authors"))